version: "3.9"

services:
  app:
    container_name: amflux-app
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    tty: true
    stdin_open: true
    # Optional: enable these when you use real hardware on Raspberry Pi
    # devices:
    #   - /dev/i2c-1:/dev/i2c-1
    #   - /dev/spidev0.0:/dev/spidev0.0
    # cap_add:
    #   - NET_ADMIN
    # network_mode: hosto