services:
  app:
    container_name: amflux-app
    image: amflux/controls-dev:latest  
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    tty: true
    stdin_open: true
    # devices:
    #   - /dev/i2c-1:/dev/i2c-1
    #   - /dev/spidev0.0:/dev/spidev0.0
    # cap_add:
    #   - NET_ADMIN
    # network_mode: host